---
 - name: "Update yum"
   command: /usr/bin/yum update -y
   remote_user: ec2-user
   sudo: yes

 - name: "install jq"
   yum: name=jq 
        state=present
   ignore_errors: true
   remote_user: ec2-user
   sudo: yes

 - name: "timezone"
   command: "{{ item }}"
   with_items: 
    - rm -f /etc/localtime
    - ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
    - echo -e 'ZONE="America/Sao_Paulo"\nUTC=true' > /etc/sysconfig/clock
   remote_user: ec2-user
   sudo: yes

 - name: "Locale"
   command: echo "LANG=pt_BR.UTF-8" > /etc/sysconfig/i18n
   remote_user: ec2-user
   sudo: yes
