---
- name: get epel
  shell: wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
  sudo: yes

- shell: sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
  sudo: yes
