---
- name: Updating alternatives to java 8
  shell: update-alternatives --set java /usr/java/default/bin/java

- name: Clonning the Project
  git: repo=git@github.com:andremidea/hystrix-exercise.git dest=/tmp/hystrix-exercise accept_hostkey=true key_file=/home/ec2-user/.ssh/id_rsa  

- name: Package
  shell: mvn clean package chdir=/tmp/hystrix-exercise/hystrix-service   
 
- name: create service directory
  file: path=/home/ec2-user/service state=directory

- name: copy wrapper files to service directory
  copy: src=/tmp/hystrix-exercise/hystrix-service/wrapper dest=/home/ec2-user/service/wrapper owner=ec2-user group=ec2-user mode=0644

- name: copy service jar to service directory
  copy: src=/tmp/hystrix-exercise/hystrix-service/target/hystrix-service-1.0-SNAPSHOT.jar dest=/home/ec2-user/service/hystrix-service.jar owner=ec2-user group=ec2-user mode=0644

- name: create symbolic link
  file: src=/home/ec2-user/service/service/hystrix-service dest=/etc/init.d/hystrix-service state=lik

  

