---
- name: Updating alternatives to java 8
  shell: update-alternatives --set java /usr/java/default/bin/java

- name: Clonning the Project
  git: repo=git@github.com:andremidea/hystrix-exercise.git dest=/tmp/hystrix-exercise accept_hostkey=true key_file=/home/ec2-user/.ssh/id_rsa  

- name: Package
  shell: mvn clean package chdir=/tmp/hystrix-exercise/hystrix-service   
 
- name: create service directory
  file: path=/home/ec2-user/service state=directory

- name: copy wrapper files to service directory
  command: creates=/home/ec2-user/service/wrapper mv /tmp/hystrix-exercise/hystrix-service/wrapper /home/ec2-user/service/wrapper

- name: copy service jar to service directory
  command: cp -f /tmp/hystrix-exercise/hystrix-service/target/hystrix-service-1.0-SNAPSHOT.jar /home/ec2-user/service/hystrix-service.jar

- name: set permissions correctly
  file: path=/home/ec2-user/service owner=ec2-user group=ec2-user recurse=yes

- name: create symbolic link
  file: src=/home/ec2-user/service/wrapper/hystrix-service dest=/etc/init.d/hystrix-service state=link

  

