---
- name: Creating VPC
  ec2_vpc:
   state: present
   cidr_block: 172.23.0.0/16
   resource_tags: { "Environment":"Development" }
   region: sa-east-1
   internet_gateway: True
   subnets:
      - cidr: 172.23.1.0/24
        az: "{{ instance[server].region }}a"            
   route_tables:
      - subnets:
           - 172.23.1.0/24        
        routes:
           - dest: 0.0.0.0/0
             gw: igw
  register: vpc

- debug: var=vpc

- name: Creating Security Group
  ec2_group:
   name: front
   description: fronts security Group - FRONT
   vpc_id: "{{vpc.vpc.id}}"
   region: "{{ instance[server].region }}"
   rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0  
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: group


- name: Creating Security Group - WEB
  ec2_group:
   name: web
   description: fronts security Group
   vpc_id: "{{vpc.vpc.id}}"
   region: "{{ instance[server].region }}"
   rules:
      - proto: all
        group_ip: group.group_id      
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
 
 
