	# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hansode/centos-6.5-x86_64"
  config.ssh.insert_key = true

    config.vm.define :web do |web|
      web.vm.network :private_network, :ip => "192.168.33.10"      
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end

      config.vm.provision "ansible" do |ansible|
		  ansible.playbook = "provisioning.yml"
		end
end
