---
- name: Creating VPC
  ec2_vpc:
   state: present
   cidr_block: 172.23.0.0/16
   resource_tags: { "Environment":"Development" }
   region: "{{ region }}"
   internet_gateway: True
   subnets:
      - cidr: 172.23.1.0/24
        az: "{{ zone }}"            
   route_tables:
      - subnets:
           - 172.23.1.0/24        
        routes:
           - dest: 0.0.0.0/0
             gw: igw
  when: vpc_id is not defined             
  register: vpc

- debug: var=vpc

- name: Creating Security Group
  ec2_group:
   name: front
   description: fronts security Group - FRONT
   vpc_id: "{{ vpc_id | | vpc.vpc.id }}"
   region: "{{region}}"
   rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0  
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: group
  when: vpc.vpc.id is defined

- debug: var=group

- name: Creating Security Group - WEB
  ec2_group:
   name: web
   description: fronts security Group
   vpc_id: "{{ vpc.vpc.id }}"
   region: "{{ region }}"
   rules:
      - proto: all        
        group_name: front
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: groupweb
  when: vpc.vpc.id is defined

- name: Creating Security Group
  ec2_group:
    name: front
    description: fronts security Group - FRONT
    vpc_id: "{{ vpc_id }}"
    region: "{{region}}"
    rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 443
         to_port: 443
         cidr_ip: 0.0.0.0/0  
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
  register: group
  when: vpc_id is defined

- debug: var=group

- name: Creating Security Group - WEB
  ec2_group:
   name: web
   description: fronts security Group
   vpc_id: "{{ vpc_id }}"
   region: "{{ region }}"
   rules:
      - proto: all        
        group_name: front
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: groupweb
  when: vpc_id is defined 
 
- debug: var=groupweb
 
 
